variables:
  SOURCE_CHIPLAB_DIR: "/home/loongson/nscscc2025_team/chiplab"
  CHIPLAB_DIR: "$CI_PROJECT_DIR/chiplab"
  VIVADO_DIR: "/home/loongson/opt/vivado2023.2/"
  FUNC_BIN_FILE_PATH: "$CHIPLAB_DIR/software/examples/nscscc_func/obj/main.bin"
  PERF_BIN_FILE_PATH: "$CHIPLAB_DIR/software/examples/nscscc_perf/obj/allbench/inst_data.bin"
  GIT_DEPTH: 0
  
workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web"'
      when: always
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: never
    - changes:
        - .gitlab-ci.yml
        - src/mycpu/**/*
        - src/perf_clk_pll.xci
      when: always
    - when: never

default:
  tags:
    - vivado2023.2
    - chiplab
  before_script:
    - source $VIVADO_DIR/Vivado/2023.2/settings64.sh
    - cp -r $SOURCE_CHIPLAB_DIR $CI_PROJECT_DIR
    - mv ./src/mycpu/* $CHIPLAB_DIR/IP/myCPU
  # image:
  #   name: "nscscc2025_team:v0.3"
  #   pull_policy: if-not-present

stages:
  - gen_bit
  - program_device

gen_func:
  stage: gen_bit
  script:
    # - source $VIVADO_DIR/Vivado/2023.2/settings64.sh
    # - cp -r $SOURCE_CHIPLAB_DIR $CHIPLAB_DIR
    # - mv ./src/mycpu/* $CHIPLAB_DIR/IP/myCPU
    # - echo "Changed files since last commit on this branch:"
    # - echo $CI_COMMIT_BEFORE_SHA
    # - echo $CI_COMMIT_SHA
    # - git diff --name-only $CI_COMMIT_BEFORE_SHA $CI_COMMIT_SHA
    # - git diff $CI_COMMIT_BEFORE_SHA $CI_COMMIT_SHA
    - sed -i '2s|.*|`define RUN_FUNC_TEST|' "$CHIPLAB_DIR/chip/soc_demo/nscscc-team/soc_config.vh"
    - sed -i '3s|.*|// `define RUN_PERF_TEST|' "$CHIPLAB_DIR/chip/soc_demo/nscscc-team/soc_config.vh"
    - cd $CHIPLAB_DIR/fpga/nscscc-team/run_vivado
    - vivado -mode batch -source create_project.tcl
    - vivado -mode batch -source bit.tcl
    - cp project/loongson.runs/impl_1/soc_top.bit ../../../../func_soc_top.bit
    - cp project/loongson.runs/impl_1/soc_top.ltx ../../../../func_soc_top.ltx
    - cp project/loongson.runs/impl_1/timing_summary.rpt ../../../../func_timing_summary.rpt || true
  artifacts:
    name: "$CI_PROJECT_NAME-func"
    # when: always
    paths:
      - func_soc_top.bit
      - func_soc_top.ltx
      - func_timing_summary.rpt

gen_perf:
  stage: gen_bit
  script:
    # - source $VIVADO_DIR/Vivado/2023.2/settings64.sh
    # - cp -r $SOURCE_CHIPLAB_DIR $CHIPLAB_DIR
    # - mv ./src/mycpu/* $CHIPLAB_DIR/IP/myCPU
    - rm $CHIPLAB_DIR/chip/soc_demo/nscscc-team/xilinx_ip/clk_pll/clk_pll.xci
    - mv ./src/perf_clk_pll.xci $CHIPLAB_DIR/chip/soc_demo/nscscc-team/xilinx_ip/clk_pll/clk_pll.xci
    - cd $CHIPLAB_DIR/fpga/nscscc-team/run_vivado
    - vivado -mode batch -source create_project.tcl
    - vivado -mode batch -source bit.tcl
    - cp project/loongson.runs/impl_1/soc_top.bit ../../../../perf_soc_top.bit
    - cp project/loongson.runs/impl_1/soc_top.ltx ../../../../perf_soc_top.ltx
    - cp project/loongson.runs/impl_1/timing_summary.rpt ../../../../perf_timing_summary.rpt || true
  artifacts:
    name: "$CI_PROJECT_NAME-perf"
    paths:
      - perf_soc_top.bit
      - perf_soc_top.ltx
      - perf_timing_summary.rpt

program_perf:
  stage: program_device
  tags:
    - hardware_server2023.2
    - chiplab
  needs:
    - job: gen_perf
      artifacts: true
  script:
    - sed -i "s|\(set bin_file \[open \"\)[^\"]*\(\" \"rb\"\]\)|\1${PERF_BIN_FILE_PATH}\2|" $CHIPLAB_DIR/fpga/nscscc-team/run_vivado/jtag_axi_master.tcl
    - mkdir $CHIPLAB_DIR/fpga/nscscc-team/run_vivado/project && cd $CHIPLAB_DIR/fpga/nscscc-team/run_vivado/project
    - vivado -mode batch -source ../vio.tcl -tclargs $CI_PROJECT_DIR/perf_soc_top.bit $CI_PROJECT_DIR/perf_soc_top.ltx perf
    - cp perf_vio.csv  $CI_PROJECT_DIR
  artifacts:
    name: "$CI_PROJECT_NAME-perf"
    paths:
      - perf_soc_top.bit
      - perf_soc_top.ltx
      - perf_timing_summary.rpt
      - perf_vio.csv

program_func:
  stage: program_device
  tags:
    - hardware_server2023.2
    - chiplab
  needs: 
    - job: gen_func
      artifacts: true
  script:
    - sed -i "s|\(set bin_file \[open \"\)[^\"]*\(\" \"rb\"\]\)|\1${FUNC_BIN_FILE_PATH}\2|" $CHIPLAB_DIR/fpga/nscscc-team/run_vivado/jtag_axi_master.tcl
    - mkdir $CHIPLAB_DIR/fpga/nscscc-team/run_vivado/project && cd $CHIPLAB_DIR/fpga/nscscc-team/run_vivado/project
    - vivado -mode batch -source ../vio.tcl -tclargs $CI_PROJECT_DIR/func_soc_top.bit $CI_PROJECT_DIR/func_soc_top.ltx func
    - cp func_vio.csv  $CI_PROJECT_DIR
  artifacts:
    name: "$CI_PROJECT_NAME-func"
    paths:
      - func_soc_top.bit
      - func_soc_top.ltx
      - func_timing_summary.rpt
      - func_vio.csv